[package]
name = "imageparse"
version = "0.0.1"
authors = ["Niels Wießner <n.h.wiessner@gmail.com>"]
license = "MIT/Apache-2.0"

[dependencies]
filebuffer = "0.3.0"
log = "0.3.6"

[dev-dependencies]
env_logger = "0.3.5"
